project:
  type: website

website:
  navbar:
    search: true
    title: false
    left:
      - text: "About"
        file: about.qmd
      - sidebar:projects
      - sidebar:contact
  
  sidebar: 
    - id: projects
      title: "Projects"
    
    - id: contact
      title: "Contact"

format:
  html:
    theme:
      dark: darkly
      light: flatly
    css: styles.css
    toc: true
    