project:
  type: website

website:
  navbar:
    search: true
    title: false
    left:
      - text: "About"
        file: about.qmd

format:
  html:
    theme:
      dark: darkly
      light: flatly
    css: styles.css
    toc: true
    