project:
  type: website

website:
  navbar:
    pinned: true
    search: true
    title: false
    left:
      - icon: house-door-fill
        text: " "
        file: index.qmd 
      - text: "Home"
        file: index.qmd
      - text: "About"
        file: about.qmd
      - text: "Projects"
        file: projects.qmd 
      - text: "Contact"
        file: contact.qmd
      - text: "CV"
        href: cv.pdf

format:
  html:
    anchor-sections: true
    smooth-scroll: true
    theme:
      dark: darkly
      light: flatly
    css: styles.css
    toc: true
    