project:
  type: website

website:
  navbar:
    left:
      - icon: house-door-fill
        href: about.qmd
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
    right: 
      - icon: github
        href: https://github.com/TimRuel
        aria-label: Github
      - icon: linkedin
        href: www.linkedin.com/in/timothy-ruel-17b45a14b
        aria-label: LinkedIn

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



