project:
  type: website

website:
  navbar:
    pinned: true
    search: true
    title: false
    left:
      - icon: house-door-fill
        text: " "
        file: index.qmd 
      - text: "Teaching"
        file: teaching.qmd
      - text: "Contact"
        file: contact.qmd
      - text: "Resume"
        file: resume4.pdf

format:
  html:
    anchor-sections: false
    smooth-scroll: false
    theme:
      dark: darkly
      light: flatly
    css: styles.css
    toc: false
    