project:
  type: website

website:
  title: "Tim Ruel"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right: 
      - icon: github
        href: https://github.com/TimRuel
        aria-label: Github

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



